version: '3.8'

services:
  server:
    build: ./server
    container_name: MY_BACKEND
    depends_on:
      - db
    env_file:
      - ./server/.env
    environment:
      WAIT_HOSTS: db:5432
    ports:
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./server:/app
    command: npm run dev
    restart: on-failure

  client:
    build: ./client
    container_name: MY_FRONTEND
    environment:
      - NODE_PATH=src
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: npm start

  db:
    container_name: MY_DATABASE
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myUsername
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: myProject
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      -  5432:5432

  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: myPassword
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    ports:
      - 8080:80
    volumes:
      - ./db/servers.json:/pgadmin4/servers.json
    logging:
      driver: none

networks:
  default:
    name: my_network